### ISSUE TITLE
How can we develop something like this? It's just GREAT. 

### ISSUE THREAD

**Issue by shriharsha-bhagwat** [varunest/TheGlowingLoader#1]
I want to develop custom animations like this. It's very inspiring. Can you let me know how we learn to develop custom animations.

**Comment by varunest** [comment]
Hi, 
I'm glad that this project inspired you. To start with you can look at the code here to understand what is happening under the hood. 
Entry point for code: https://github.com/varunest/TheGlowingLoader/blob/master/theglowingloader/src/main/java/com/varunest/loader/TheGlowingLoader.java
