### ISSUE TITLE
Executing setConfiguration()

### ISSUE THREAD

**Issue by AbdiasVrech** [varunest/TheGlowingLoader#2]
Hi man! this code is awesome.

I just wanted to share with you that I've just added to my code, but noticed that when i call the method `setConfiguration(config);` it doesn't execute.

So I re-wrote your code just to add this simple line after calling that methode (I share it with you in case that you want to correct it, I've already solve my problem)

```
public void setConfiguration(Configuration configuration) {
        this.configuration = configuration;
        **init();**
}
```

Greetings

**Comment by varunest** [comment]
Good catch. Thank you. 
Will update.
