### ISSUE TITLE
setConfiguration not working

### ISSUE THREAD

**Issue by aci9evil** [varunest/TheGlowingLoader#3]
configuration.setLine1Color, configuration.setLine2Color, configuration.setDisableShadows is not working((
but configuration.setDisableRipple is working.

**Comment by aci9evil** [comment]
can't implementation 'com.github.varunest:TheGlowingLoader:1.0.6'

**Comment by salierykuba** [comment]
> can't implementation 'com.github.varunest:TheGlowingLoader:1.0.6'

because the last version is: 1.0.5; not: 1.0.6, like the author says.

**Comment by varunest** [comment]
apologies, something didn't go right in last release. Released 1.0.7, it should have the fix.
